version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore AspNetCoreWebApplication/AspNetCoreWebApplication.csproj
      - dotnet restore AspNetCoreWebApplicationTest/AspNetCoreWebApplicationTest.csproj
      - dotnet tool install --global dotnet-coverage
      - ldd --version
      - xml2-config --version
  build:
    commands:
      - dotnet publish -c release -o ./build_output AspNetCoreWebApplication/AspNetCoreWebApplication.csproj
      - dotnet publish -c release -o ./test_output AspNetCoreWebApplicationTest/AspNetCoreWebApplicationTest.csproj
      - dotnet test AspNetCoreWebApplicationTest/bin/release/net6.0/AspNetCoreWebApplicationTest.dll
      - dotnet-coverage collect "dotnet test" -f xml -o coverage.xml
  post_build:
    commands:

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      
artifacts:
  files:
    - template.yml
    - AspNetCoreWebApplication/bin/**/*
    - AspNetCoreWebApplication/wwwroot/**/*
    - scripts/**/*
    - appspec.yml
    - requirements.txt
    - template-configuration.json
    - coverage.xml

reports:
  coverage-report:
    files:
      - 'coverage.xml'
    file-format: 'COBERTURAXML'
